import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    id 'java'
    id 'xyz.wagyourtail.unimined' version '1.4.2-SNAPSHOT'
    id 'com.gradleup.shadow' version '8.3.11'
}

group 'dev.safixo'
version '1.0'

base.archivesName = 'kronos'

// this is just here so we can test the outputs easier and clean between tests
unimined.useGlobalCache = true

sourceCompatibility = JavaVersion.VERSION_1_7
targetCompatibility = JavaVersion.VERSION_1_7

unimined.minecraft {
    sourceCompatibility = JavaVersion.VERSION_1_7
    targetCompatibility = JavaVersion.VERSION_1_7

    version "1.6.4"

    minecraftForge {
        loader "9.11.1.1345"
        accessTransformer("src/main/resources/kronos_at.cfg")
    }
}

dependencies {
    // https://mvnrepository.com/artifact/it.unimi.dsi/fastutil
    implementation("it.unimi.dsi:fastutil:7.2.1")
    // https://mvnrepository.com/artifact/org.joml/joml
    implementation("org.joml:joml:1.9.20")
    // https://mvnrepository.com/artifact/org.lwjgl.lwjgl/lwjgl
    compileOnly("org.lwjgl.lwjgl:lwjgl:2.9.1")

    // https://mvnrepository.com/artifact/it.unimi.dsi/fastutil
    shadow("it.unimi.dsi:fastutil:7.2.1")
    // https://mvnrepository.com/artifact/org.joml/joml
    shadow("org.joml:joml:1.9.20")
}

tasks.register("shadowRemapJar", ShadowJar) {
    configurations = [project.configurations.shadow]
    archiveClassifier = 'all'

    from {
        zipTree(tasks.named("remapJar").get().archiveFile)
    }
    getManifest().inheritFrom(jar.getManifest())

    exclude 'module-info.class'
    minimize()
}

build.dependsOn(tasks.named("shadowRemapJar"))

jar {
    manifest.attributes([
            "FMLCorePlugin": "dev.safixo.KronosCoreMod",
            "FMLCorePluginContainsFMLMod": "true",
            "ForceLoadAsMod": "true"
    ])
}

runClient {
    jvmArgs += "-Dfml.coreMods.load=dev.safixo.KronosCoreMod"
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
    }

    filesMatching("mcmod.info") {
        expand "version": project.version
    }
}
