plugins {
    id 'java'
    id 'xyz.wagyourtail.unimined' version '1.4.1'
}

group 'dev.safixo'
version '1.0-SNAPSHOT'

base {
    archivesName = 'kronos'
}

// this is just here so we can test the outputs easier and clean between tests
unimined.useGlobalCache = false

sourceCompatibility = JavaVersion.VERSION_1_7
targetCompatibility = JavaVersion.VERSION_1_7

unimined.minecraft {
    sourceCompatibility = JavaVersion.VERSION_1_7
    targetCompatibility = JavaVersion.VERSION_1_7

    version "1.6.4"

    minecraftForge {
        loader "9.11.1.1345"
    }

    minecraftRemapper.config {
        ignoreConflicts(true)
    }
}

repositories {

}

dependencies {
    // https://mvnrepository.com/artifact/it.unimi.dsi/fastutil
    implementation('it.unimi.dsi:fastutil:7.1.0')
    // https://mvnrepository.com/artifact/org.joml/joml
    implementation("org.joml:joml:1.9.20")
}

jar {
    manifest {
        attributes(
                'FMLCorePlugin': 'dev.safixo.KronosCoreMod'
        )
    }

//    from { configurations.runtimeClasspath.collect { zipTree(it) } }
//    exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'
}

tasks.named("runClient") {
    jvmArgs += ["-Dfml.coreMods.load=dev.safixo.KronosCoreMod"]
}

tasks.withType(JavaExec).configureEach {
    doFirst {
        classpath = classpath.filter { file ->
            !file.name.contains('annotations')
        }
    }
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
    }

    filesMatching("mcmod.info") {
        expand "version": project.version
    }
}
